// content-loader.js (Path corrected version for deployed HTML files)

class ContentLoader {
    constructor() {
        this.init();
    }

    async init() {
        await this.loadContent();
    }

    async loadContent() {
        try {
            // Load HTML files generated by build.py from the root of the deployed site
            const introContent = await this.loadHtml('introduction.html');
            this.updateSection('introduction', introContent);

            const conceptContent = await this.loadHtml('concept.html');
            this.updateSection('concept', conceptContent);

            const tracksContent = await this.loadHtml('tracks.html');
            this.updateSection('tracks', tracksContent);

        } catch (error) {
            console.log('Content files not found, using default content', error);
        }
    }

    async loadHtml(filePath) {
        try {
            const response = await fetch(filePath);
            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            const text = await response.text();
            return text; // HTMLはそのまま返す
        } catch (error) {
            console.error(`Could not load ${filePath}:`, error);
            return null;
        }
    }

    // Markdownのパースは不要になったため削除
    // parseMarkdown(markdown) {
    //     ...
    // }

    updateSection(sectionId, content) {
        if (!content) return;

        const section = document.getElementById(sectionId);
        if (section) {
            const placeholder = section.querySelector('.content-placeholder');
            if (placeholder) {
                placeholder.innerHTML = content;
            }
        }
    }
}

document.addEventListener('DOMContentLoaded', () => {
    new ContentLoader();
});
